### ISSUE TITLE
add icbit.se/

### ISSUE THREAD

**Issue by algazarra** [drpout/boilr#205] opened 2015-04-24 12:02 UTC
https://icbit.se/WebTrade/Account/API.aspx

**Comment by dllud** [comment] 2015-04-24 15:03
Seems it was merged with https://orderbook.net At least https://icbit.se points there.
Therefore duplicate of #109.

Also there is no way do check the API without logging in and I find no way to open an account.

**Closed by dllud** 2015-04-24 15:03 UTC
Labels: enhancement
