### ISSUE TITLE
Can't delete/ change type of old alarms

### ISSUE THREAD

**Issue by Raketenwilli** [drpout/boilr#263] opened 2017-07-28 09:53 UTC
Is it possible to delete old alarms?

**Comment by dllud** [comment] 2017-07-28 12:15
Yes. Just swipe them:

![deleting-alarm](https://user-images.githubusercontent.com/1716156/28716727-a958ee80-7396-11e7-9cda-2e25163f1889.png)

(Duplicate of #254)

**Closed by dllud** 2017-07-28 12:15 UTC
Labels: duplicate, question
