### ISSUE TITLE
Kraken pairs not working, bug with currency code?

### ISSUE THREAD

**Issue by fm444fm** [drpout/boilr#276] opened 2017-10-17 15:14 UTC
There are several pairs (CH/*, ASH/*, OS/*, NO/*, SDT/*) of currencies not working on kraken.
Should maybe CH be actually BCH? ASH > DASH, OS > EOS, NO > GNO, SDT > USDT?
It seems for these pairs the first letter is missing and hence "cannot retrieve last value..." message appears

**Comment by dllud** [comment] 2017-10-18 00:35
Duplicate of #273

**Closed by dllud** 2017-10-18 00:35 UTC
Labels: duplicate
